"""add_event_registrations_table

Revision ID: d9bebebd4437
Revises: febfea00f420
Create Date: 2026-03-06 13:51:48.971239

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d9bebebd4437"
down_revision: str | Sequence[str] | None = "febfea00f420"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_registrations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "cancelled", name="registrationstatus"),
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "registered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_event_registrations_event_active",
        "event_registrations",
        ["event_id"],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
        sqlite_where=sa.text("status = 'active'"),
    )
    op.create_index(
        "ix_event_registrations_user_registered",
        "event_registrations",
        ["user_id", "registered_at"],
        unique=False,
    )
    op.create_index(
        "uq_active_registration",
        "event_registrations",
        ["user_id", "event_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
        sqlite_where=sa.text("status = 'active'"),
    )
    op.add_column(
        "events",
        sa.Column(
            "current_participants", sa.Integer(), server_default="0", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "current_participants")
    op.drop_index(
        "uq_active_registration",
        table_name="event_registrations",
        postgresql_where=sa.text("status = 'active'"),
        sqlite_where=sa.text("status = 'active'"),
    )
    op.drop_index(
        "ix_event_registrations_user_registered", table_name="event_registrations"
    )
    op.drop_index(
        "ix_event_registrations_event_active",
        table_name="event_registrations",
        postgresql_where=sa.text("status = 'active'"),
        sqlite_where=sa.text("status = 'active'"),
    )
    op.drop_table("event_registrations")
    # ### end Alembic commands ###
