"""add_events_table

Revision ID: febfea00f420
Revises: 7775aa36a5b2
Create Date: 2026-03-06 13:06:54.677492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'febfea00f420'
down_revision: Union[str, Sequence[str], None] = '7775aa36a5b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('registration_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quota', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'deleted', name='eventstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quota >= 1', name='chk_quota_positive'),
    sa.CheckConstraint('registration_deadline <= date', name='chk_deadline_before_date'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_date_title', 'events', ['date', 'title'], unique=False)
    op.create_index('ix_events_registration_deadline', 'events', ['registration_deadline'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_registration_deadline', table_name='events')
    op.drop_index('ix_events_date_title', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
